### PR TITLE
Adds available drush Options

### PR DESCRIPTION
**Pull request by DonRichards**
**JIRA Ticket**: N/A

# What does this Pull Request do?
Adds to README.md the drush options

# What's new?
Adds a small chunk of text from the drush help list. 

# How should this be tested?
run the `drush help islandora_book_batch_preprocess` command and see if the results are the same. 

# Additional Notes:
Not sure if the "needs" to be part of the release or not.

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Review by DiegoPino — APPROVED** [review]
Ok, documentation, so can you make a release equivalent? looks good

**Comment by DonRichards** [comment]
Yes, I can.

**Comment by DonRichards** [comment]
@DiegoPino Do you have the ability to make settings changes on this repo? The requirement for approval isn't set. It says I can merge immediately without approving.

**Comment by DiegoPino** [comment]
Hi, you can merge because I approved. The restriction is set for this branch. Just checked. 1.11 has not, you mean 1.11?

**Comment by DonRichards** [comment]
Yes 1.11 did the same.

**Pull request merged**
